config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'player/simple'
  get 'player/car'

  resources :playlists
  devise_for :users
  resources :pages

  get 'pages/home'

  resources :home, only: [:index]
  get 'home/home'
  get 'home/search'
  get 'home/search_form'
  get 'home/search_results'
  get 'home/playlist'
  get 'home/player'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artist, only: [:show]

  resources :audio_files, only: [] do
    member do
      get 'add'
    end
  end

  resources :artists, only: [] do
    resources :albums, only: [] do
      get 'add'
    end
  end

  resources :albums, only: [:show] do
    member do
      get 'image'
      get 'add'
    end
  end

  get 'list_nodes/clear'
  get 'list_nodes/flatten'
  get 'list_nodes/move_to'
  get 'list_nodes/add_to_playing'
  post 'list_nodes/playlist_playable_items'
  resources :list_nodes, only: %i[index destroy]

  root to: 'home#index'
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_many :audio_files, dependent: :nullify
  has_many :albums, through: :audio_files
  has_many :songs, through: :audio_files
  has_many :genres, through: :audio_files
  has_many :file_dirs, through: :audio_files
  has_many :solo_albums, foreign_key: :album_artist_id, class_name: 'Album'
  has_many :lyrics

  validates :name, presence: true, uniqueness: true

  def album_names
    albums.map(&:name).join(' ')
  end

  searchable auto_index: true,
             auto_remove: true,
             include: [:albums] do
    integer :id

    string :name

    text :name_text, boost: 0.9 do
      name
    end

    text :name_textp, stored: true, boost: 0.5, as: :name_textp do
      name
    end

    text :album_names, boost: 0.2 do
      album_names
    end
  end
end

app/views/artists/_album.html.haml
-# image_file = album.album_image_file
-# image_url = image_file ? image_file.imageurl : "256x256/devices/media-optical-audio_mount.png"
.elem.Artist.Album.playable{:id => "sr-artist-#{artist.id}-album-#{album.id}", 'data-elem_id' => "album-#{album.id}"}
  .elem-image.float-left
    = link_to %{<img src="#{image_url(album,'small')}" border="0" />}.html_safe, artist_album_add_path(artist.id,album.id), :remote => true, :title => "Add '#{album.name}' to Playing"
  .elem-data
    .name=link_to album.name, album_path(album.id), :class => 'link-name'

app/views/artists/_elem.html.haml
- all_albums = elem.albums.uniq
- all_tracks = all_albums.map{|alb| alb.audio_files.limit_to(elem) }.flatten
.elem.Artist{ 'data-elem_id' => "#{elem.class.to_s.tableize}-#{elem.id}" } 
  .elem-data
    .name
      = link_to elem.name, artist_path(elem.id), :class => 'link-name'
      %span{ :class => 'artist-subname' }
        = '(' + pluralize(all_albums.size,'album') + ')'
      %span{ :class => 'artist-subname' }
        = '(' + pluralize(all_tracks.size,'track') + ')'
  .elem-content
    - albs = (elem.solo_albums + elem.albums).uniq
    
    - albs.each do |alb|
      .row
        .col-sm-12.col-md-6.col-lg-4
          = render :partial => 'artists/album', :object => alb, :locals => { :artist => elem }

app/views/artists/_elem_body.html.haml
- albs = (elem.solo_albums + elem.albums).uniq

.row
  - albs.each do |album|
    .col-sm-12.col-md-12.col-lg-6
      .alb-col
        .image.float-left
          = link_to %{<img src="#{image_url(elem,album)}" border="0" />}.html_safe, artist_album_add_path(elem.id,album.id), :remote => true, :title => "Add '#{album.name}' to Playing"
        .name
          = link_to album.name, search_query(album.name), :class => 'link-name query-link'

app/views/artists/_elem_head.html.haml
.name
  = link_to elem.name, search_query(elem.name), :class => 'link-name query-link'
  %span.subname
    = '( ' + pluralize(elem.audio_files.uniq.count,'track') + ' )'
  &nbsp;
  %span.subname
    = '( ' + pluralize(elem.albums.uniq.count,'album') + ' )'