config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'player/simple'
  get 'player/car'

  resources :playlists
  devise_for :users
  resources :pages

  get 'pages/home'

  resources :home, only: [:index]
  get 'home/home'
  get 'home/search'
  get 'home/search_form'
  get 'home/search_results'
  get 'home/playlist'
  get 'home/player'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artist, only: [:show]

  resources :audio_files, only: [] do
    member do
      get 'add'
    end
  end

  resources :artists, only: [] do
    resources :albums, only: [] do
      get 'add'
    end
  end

  resources :albums, only: [:show] do
    member do
      get 'image'
      get 'add'
    end
  end

  get 'list_nodes/clear'
  get 'list_nodes/flatten'
  get 'list_nodes/move_to'
  get 'list_nodes/add_to_playing'
  post 'list_nodes/playlist_playable_items'
  resources :list_nodes, only: %i[index destroy]

  root to: 'home#index'
end

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/home.js.erb
$('#home-display').replaceWith("<%= escape_javascript(render(:partial => 'pages/jumbo')) %>");

app/views/pages/index.html.haml
#search-page
  .container
    #search-form
  .container
    #search-results

#home-page
  .jumbotron      
    .container
      #home-display

#playlist-page
  .container
    #playlist

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p
  %b Title:
  = @page.title

= link_to 'Edit', edit_page_path(@page)
\|
= link_to 'Back', pages_path