config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'player/simple'
  get 'player/car'

  resources :playlists
  devise_for :users
  resources :pages

  get 'pages/home'

  resources :home, only: [:index]
  get 'home/home'
  get 'home/search'
  get 'home/search_form'
  get 'home/search_results'
  get 'home/playlist'
  get 'home/player'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artist, only: [:show]

  resources :audio_files, only: [] do
    member do
      get 'add'
    end
  end

  resources :artists, only: [] do
    resources :albums, only: [] do
      get 'add'
    end
  end

  resources :albums, only: [:show] do
    member do
      get 'image'
      get 'add'
    end
  end

  get 'list_nodes/clear'
  get 'list_nodes/flatten'
  get 'list_nodes/move_to'
  get 'list_nodes/add_to_playing'
  post 'list_nodes/playlist_playable_items'
  resources :list_nodes, only: %i[index destroy]

  root to: 'home#index'
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  belongs_to :album_dir, class_name: 'FileDir'
  belongs_to :album_artist, class_name: 'Artist'
  belongs_to :album_image_file, class_name: 'ImageFile'

  has_many :audio_files, dependent: :nullify
  has_many :artists, through: :audio_files
  has_many :songs, through: :audio_files
  has_many :genres, through: :audio_files
  has_many :file_dirs, through: :audio_files
  has_many :image_files, through: :file_dirs
  has_many :list_nodes, as: :listable

  validates :name, presence: true, uniqueness: { scope: :album_dir_id }

  searchable auto_index: true, auto_remove: true do
    integer :id

    string :name
    text :name_text, boost: 0.9 do
      name
    end
    text :name_textp, stored: true, boost: 0.5, as: :name_textp do
      name
    end
  end

  def album_artist_name
    album_artist ? album_artist.name : nil
  end

  def create_list_node_all(parent, filter_recs = [])
    new_node = parent.children.create(listable: self)
    create_list_node_children(new_node, filter_recs)
  end

  def create_list_node(parent)
    parent.children.create(listable: self)
  end

  def create_list_node_children(parent, filter_recs = [])
    audio_files.limit_to(*filter_recs).order('tracknum').each do |af|
      af.create_list_node(parent)
    end
    parent
  end

  def node_class(node)
    classes = ''
    audio_files = node.children.all.map(&:listable)
    artists = audio_files.map(&:artist)
    classes += if artists.uniq.size == 1
                 'single-artist'
               else
                 'multi-artist'
               end
    classes
  end
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

require 'filemagic'
class AlbumsController < ApplicationController
  layout(proc { |controller| controller.request.xhr? ? false : 'application' })

  # def altimg(album, size = 'medium')
  #   artist = album.album_artist
  #   if artist
  #     album_name = album.name
  #     artist_name = artist.name
  #     altdir = "/srv/data/lastfm2/album/#{artist_name}/#{album_name}/cover"
  #     imgfilebase = altdir + '/' + size + '.'
  #     %w[jpg png].each do |ext|
  #       imgfile = imgfilebase + ext
  #       return imgfile if ::File.exist?(imgfile)
  #     end
  #   end
  #   nil
  # end

  # def image
  #   album = Album.includes(:album_artist).find(params[:id])
  #   sz = params[:sz]
  #   filepath = altimg(album, sz || 'medium')
  #   unless filepath
  #     image_file = album.album_image_file
  #     filepath = if image_file
  #                  image_file.filepath
  #                else
  #                  'app/assets/images/64x64/devices/media-optical-audio_mount.png'
  #                end
  #   end

  #   mime_type = image_file.mime_type if image_file
  #   Rails.logger.info('filepath = ' + filepath.inspect)
  #   mime_type ||= FileMagic.open(:mime_type).file(filepath)

  #   response.headers['Cache-Control'] = "public, max-age=#{7.days.to_i}"
  #   response.headers['Content-Type'] = mime_type
  #   response.headers['Content-Disposition'] = 'inline'
  #   content = open(filepath, 'rb').read
  #   response.headers['Content-Length'] = content.size.to_s

  #   render plain: content
  # end

  def add
    @artist_id = params[:artist_id]
    @id = params[:album_id] || params[:id]

    list_node = current_user.list_heads.playing.first.list_node
    artists = @artist_id ? [Artist.find(@artist_id.to_i)] : []
    new_node = Album.find(@id).create_list_node_all(list_node, artists)

    @node_id = new_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
  def image_url(artist,album)
    if artist
      album_name = album.name
      artist_name = artist.name
      path = "/#{artist_name}/#{album_name}/image.jpg"
      url = 'http://images.kitatdot.net' + path
    end
    url
  end

  def coverart_url(album, size = 'medium')
    artist = album.album_artist
    if artist
      album_name = album.name
      artist_name = artist.name
      path = "/#{artist_name}/#{album_name}/cover/#{size}.jpg"
      url = 'http://albumart.kitatdot.net' + path
    end
    url
  end

  def albumart_url(album, _size = 'medium')
    # coverart_url(album,size)
    image_file = album.album_image_file
    if image_file
      image_file.imageurl
    else
      Rails.configuration.media['image_url'].sub(%r{/+$}, '') + '/media-optical-audio_mount.png'
    end
  end
end

app/views/albums/_controls.html.haml
.listnode-controls
  .listnode-ctl.float-right
    = link_to '<i class="material-icons md-18">delete</i>'.html_safe,list_node_path(id: list_node.id), :method => :delete, :title => "Remove Album From Playlist", :remote => true, :class => "remove-node"
  .listnode-ctl.float-right
    = link_to '<i class="material-icons md-18">list</i>'.html_safe,list_nodes_flatten_path(:id => list_node.id), :method => :get, :title => "Move Individual Album tracks to Playlist", :remote => true, :class => "flatten-node"
  

app/views/albums/_elem.html.haml
-# image_file = elem.album_image_file
-# image_url = image_file ? image_file.imageurl : "256x256/devices/media-optical-audio_mount.png"
- artists = elem.artists.uniq
- artist = elem.album_artist || artists.first
.elem.Album{ 'data-elem_id' => "album-#{elem.id}" } 
  .elem-image
    = link_to %{<img src="#{image_url(artist,elem)}" border="0" />}.html_safe, add_album_path(elem.id), :remote => true
  .elem-data
    .name
      = elem.name
  .elem-content
    .artists
      = artists.first(3).map(&:name).join(", ").html_safe
      = (artists.size > 3 ? " &hellip;".html_safe : "")
    - if elem.audio_files
      - if tracks
        .tracks
          %table.table.table-striped.table-condensed
            - elem.audio_files.each do |af|
              = render :partial => af, :locals => {:context_rec => elem }
      - else
        .audio_files
          - audio_files = elem.audio_files.uniq
          = audio_files.first(3).map{|a| a.name }.join(", ").html_safe
          = (audio_files.size > 3 ? " &hellip;".html_safe : "")


    

app/views/albums/_elem_body.html.haml
.row
  .col-sm-12
    - if elem.audio_files
      .audio_files
        - audio_files = elem.audio_files.uniq
        - af_links = audio_files.first(12).map{|a| link_to a.name, search_query(a.name), class: 'query-link'}
        = af_links.join("&nbsp;&nbsp;&#x2b26;&nbsp;&nbsp;").html_safe
        = (audio_files.size > 12 ? " &hellip;".html_safe : "")

app/views/albums/_elem_head.html.haml
.image.float-left
  = link_to %{<img src="#{albumart_url(elem,'medium')}" border="0" />}.html_safe, add_album_path(elem.id), :remote => true
.desc
  .row.name
    .col-sm-12
      %strong
        = link_to elem.name, search_query(elem.name), :class => 'query-link'
  .row.artist
    .col-sm-12
      %em
        - artists = elem.artists.uniq
        - artist_links = artists.first(3).map{|a| link_to a.name, search_query(a.name), class: 'query-link'}
        = artist_links.join(" &#x25c6; ").html_safe
        = (artists.size > 3 ? " &hellip;".html_safe : "")
  

app/views/albums/_elem_playlist.html.haml
.image.float-left
  = link_to %{<img src="#{albumart_url(elem,'medium')}" border="0" />}.html_safe, add_album_path(elem.id), :remote => true
.desc
  .row.name
    .col-sm-12
      %strong= elem.name
  .row.artist
    .col-sm-12
      %em
        - artists = elem.artists.uniq
        = artists.first(3).map(&:name).join(" &#x25c6; ").html_safe
        = (artists.size > 3 ? " &hellip;".html_safe : "")
  

app/views/albums/add.js.erb
$('#playing-playlist').find('.ListHead.listnode-content').append("<%= escape_javascript(render(:partial => 'list_nodes/node',:locals => { :nodetree => @nodetree, :node_id => @node_id } )) %>");

console.log("add.js.erb: before playlist()")
$('#playing-playlist').playlist();
$('.playlistchanged').trigger('playlistchanged');