config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'player/simple'
  get 'player/car'

  resources :playlists
  devise_for :users
  resources :pages

  get 'pages/home'

  resources :home, only: [:index]
  get 'home/home'
  get 'home/search'
  get 'home/search_form'
  get 'home/search_results'
  get 'home/playlist'
  get 'home/player'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artist, only: [:show]

  resources :audio_files, only: [] do
    member do
      get 'add'
    end
  end

  resources :artists, only: [] do
    resources :albums, only: [] do
      get 'add'
    end
  end

  resources :albums, only: [:show] do
    member do
      get 'image'
      get 'add'
    end
  end

  get 'list_nodes/clear'
  get 'list_nodes/flatten'
  get 'list_nodes/move_to'
  get 'list_nodes/add_to_playing'
  post 'list_nodes/playlist_playable_items'
  resources :list_nodes, only: %i[index destroy]

  root to: 'home#index'
end

app/models/audio_file.rb
# frozen_string_literal: true

class AudioFile < ApplicationRecord
  belongs_to :file_dir
  belongs_to :artist
  belongs_to :album
  belongs_to :song
  belongs_to :genre

  has_many :audio_files_tags
  has_many :tags, through: :audio_files_tags
  has_many :list_nodes, as: :listable

  validates :tracknum, numericality: true, allow_nil: true
  validates :bitrate, numericality: true, allow_nil: true
  validates :samplerate, numericality: true, allow_nil: true
  validates :length, numericality: true, allow_nil: true
  validates :layer, numericality: true, allow_nil: true
  validates :mpeg_version, numericality: true, allow_nil: true

  searchable auto_index: true,
             auto_remove: true,
             include: [{ song: :lyrics }, { artist: :lyrics }, :album] do
    integer :id

    text :song_name, boost: 0.7 do
      song_name
    end

    text :song_name_textp, stored: true, boost: 0.1, as: :name_textp do
      song ? song.name : ''
    end

    text :artist_name, boost: 0.1 do
      artist ? artist.name : ''
    end

    text :album_name, boost: 0.3 do
      album ? album.name : ''
    end

    text :lyric_text, stored: true, boost: 0.05, as: :lyric_text_textp do
      artist_lyric_ids = artist.lyrics.map(&:id)
      song.lyrics.select { |l| artist_lyric_ids.include?(l.id) }.map(&:text).join(' ')
    end

    integer :artist_id, references: Artist
    integer :album_id, references: Album
    integer :song_id, references: Song
  end

  def create_list_node(list_node, pos = nil)
    pos ||= list_node.child_ids.size + 1
    list_node.children.create(listable: self, position: pos)
  end

  alias create_list_node_all create_list_node

  def create_list_node_children(list_node, _unused = nil)
    list_node
  end

  def lyric
    lyrics.includes(:artist, :song).where(artist_id: artist.id, song_id: song.id).first
    # Lyric.where(artist_id: artist_id, song_id: song_id).first
  end

  def self.limit_to(*els)
    els.flatten.inject(all) do |combined_scope, el|
      combined_scope.where(el.class.to_s.foreign_key.to_sym => el.id)
    end
  end

  def artist_name
    artist.name if artist
  end

  def album_name
    album.name if album
  end

  def song_name
    song.name if song
  end

  def file_dir_name
    file_dir.name if file_dir
  end

  def name
    song.name
  end

  def filepath
    [file_dir.name, filename].join('/')
  end

  def fileurl
    filepath.sub('/srv/mp3/', '')
  end

  def rooturl
    Rails.configuration.media['audio_url'].sub(%r{/+$}, '')
  end

  def url
    rooturl + '/' + URI.escape(fileurl)
  end

  def duration
    Time.at(length).strftime('%M:%S').sub(/^0/, '')
  end

  def node_class(_node)
    ''
  end
end

app/controllers/audio_files_controller.rb
# frozen_string_literal: true

class AudioFilesController < ApplicationController
  layout(proc { |controller| controller.request.xhr? ? false : 'application' })

  def add
    @id = params[:id]
    list_node = current_user.list_heads.playing.first.list_node
    new_node = AudioFile.find(@id).create_list_node(list_node)
    @node_id = new_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)
    respond_to do |format|
      format.js
    end
  end
end

app/views/audio_files/_controls.html.haml
.listnode-controls
  .listnode-ctl
    = link_to '<i class="material-icons md-18">delete</i>'.html_safe,list_node_path(list_node.id), :method => :delete, :title => "Remove Song From Playlist", :remote => true, :class => "remove-node"

app/views/audio_files/_elem.html.haml
.elem.AudioFile{ 'data-elem_id' => "audio_file-#{elem.id}" } 
  .elem-image
    = link_to image_tag("note-blue-32.png"), add_audio_file_path(elem.id), :remote => true, :title => "Add '#{elem.song_name}' to Playing"
  .elem-data{ "data-sound_id" => "sound_id-audio_file-#{elem.id}", :class => "sound_id-AudioFile"}
    .duration
      = Time.at(elem.length).strftime("%M:%S").sub(/^0/,'')
    .tracknum
      = elem.tracknum
    .song.font-weight-bold.text-left
      = elem.song_name
    .artist.text-left
      = elem.artist_name
    .album
      = elem.album_name
    .url
      = link_to "#{elem.song_name} - #{elem.artist_name}",elem.url,:remote => true, :class => 'audiofile-link'

app/views/audio_files/_elem_head.html.haml
.image.float-left
  = link_to image_tag("note-blue-32.png"), add_audio_file_path(elem.id), :remote => true, :title => "Add '#{elem.song_name}' to Playing"
.data{ "data-sound_id" => "sound_id-audio_file-#{elem.id}", :class => "sound_id-AudioFile"}
  .duration.float-right
    = Time.at(elem.length).strftime("%M:%S").sub(/^0/,'')
  .tracknum
    = elem.tracknum
  .song
    = link_to elem.song_name, search_query(elem.song_name), :class => 'query-link'
  .artist.float-left
    = link_to elem.artist_name, search_query(elem.artist_name), :class => 'query-link'
  .album.float-right
    = link_to elem.album_name, search_query(elem.album_name), :class => 'query-link'
  .url
    = link_to "#{elem.song_name} - #{elem.artist_name}",elem.url,:remote => true, :class => 'audiofile-link'
  

app/views/audio_files/_elem_playlist.html.haml
.image.float-left
  = link_to image_tag("note-blue-32.png"), add_audio_file_path(elem.id), :remote => true, :title => "Add '#{elem.song_name}' to Playing"
.data{ "data-sound_id" => "sound_id-audio_file-#{elem.id}", :class => "sound_id-AudioFile"}
  .duration.float-right
    = Time.at(elem.length).strftime("%M:%S").sub(/^0/,'')
  .tracknum
    = elem.tracknum
  .song
    = elem.song_name
  .artist.float-left
    = elem.artist_name
  .album.float-right
    = elem.album_name
  .url
    = link_to "#{elem.song_name} - #{elem.artist_name}",elem.url,:remote => true, :class => 'audiofile-link'
  

app/views/audio_files/add.js.erb
$('#playing-playlist').find('.ListHead.listnode-content').append("<%= escape_javascript(render(:partial => 'list_nodes/node',:locals => { :nodetree => @nodetree, :node_id => @node_id } )) %>");

console.log("add.js.erb: before playlist()")
$('#playing-playlist').playlist();
$('.playlistchanged').trigger('playlistchanged');